Name: 04 Pitcher Adjustments
true:
  workflow_dispatch: null
  workflow_run:
    workflows:
    - 03 Batter Adjustments
    types:
    - completed
permissions:
  contents: write
concurrency:
  group: 04_pitcher_adjustments-${{ github.ref }}
  cancel-in-progress: false
jobs:
  pitcher_adjustments:
    runs-on: ubuntu-latest
    steps:
    - name: Banner
      run: 'echo "04 START $(TZ=America/New_York date)"

        echo "event_name=${{ github.event_name }}"

        echo "triggered_by=${{ github.event.workflow_run.name || ''manual'' }}"

        echo "conclusion=${{ github.event.workflow_run.conclusion || ''manual'' }}"

        '
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - name: Configure Git
      run: 'git config user.name "github-actions"

        git config user.email "github-actions@github.com"

        '
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py-${{ hashFiles('requirements.txt') }}
        restore-keys: ${{ runner.os }}-py-
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install deps
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        '
    - name: Run stage with unified logs
      shell: bash
      run: "set +e\nmkdir -p summaries/pitchers_adjust\nSTATUS=\"summaries/pitchers_adjust/status.txt\"\
        \nLOG=\"summaries/pitchers_adjust/log.txt\"\nERR=\"summaries/pitchers_adjust/errors.txt\"\
        \nSUM=\"summaries/pitchers_adjust/summary.txt\"\n: >\"$STATUS\"; : >\"$LOG\"\
        ; : >\"$ERR\"; : >\"$SUM\"\n\nts(){ TZ=\"America/New_York\" date +\"%Y-%m-%d\
        \ %I:%M:%S %p %Z\"; }\nrun_step(){ echo \"\u25B6\uFE0F START: $1 ($(ts))\"\
        \ >>\"$LOG\"; shift; \"$@\" >>\"$LOG\" 2>step.err; rc=$?; if [ $rc -eq 0 ];\
        \ then echo \"\u2705 $1 succeeded [$(ts)]\" >>\"$STATUS\"; else echo \"\u274C\
        \ $1 failed [$(ts)]\" >>\"$STATUS\"; { echo \"\u274C $1 ERROR [$(ts)]:\"\n\
        \  cat step.err; echo; echo '---'; echo; } >>\"$ERR\"; fi; rm -f step.err;\
        \ echo \"\u23F9\uFE0F END: $1 ($(ts))\" >>\"$LOG\"; echo >>\"$LOG\"; }\n\n\
        run_step normalize_pitcher_weather_outputs.py python scripts/normalize_pitcher_weather_outputs.py\n\
        run_step apply_pitcher_weather_adjustment.py  python scripts/apply_pitcher_weather_adjustment.py\n\
        run_step apply_pitcher_park_adjustment.py     python scripts/apply_pitcher_park_adjustment.py\n\
        run_step combine_pitcher_weather_park_home.py python scripts/combine_pitcher_weather_park_home.py\n\
        run_step combine_pitcher_weather_park_away.py python scripts/combine_pitcher_weather_park_away.py\n\
        \n{\n  echo \"===== RUN TIMESTAMP: $(ts) =====\"\n  echo\n  echo \"===== STATUS\
        \ =====\";  cat \"$STATUS\"\n  echo; echo \"===== LOG =====\";     cat \"\
        $LOG\"\n  echo; echo \"===== ERRORS =====\";  cat \"$ERR\"\n} > \"$SUM\"\n"
    - name: Commit stage outputs
      run: 'git add data/adjusted/pitchers_*_{weather,park}.csv || true

        git add data/adjusted/pitchers_*_weather_park.csv || true

        git add summaries/pitchers_adjust/* || true

        git diff --cached --quiet || git commit -m "04 pitcher adjustments outputs"

        git pull --rebase origin main || true

        git push origin HEAD:main || true

        '
'on':
  workflow_dispatch: {}
  workflow_run:
    workflows:
    - 03 Batter Adjustments
    types:
    - completed
