name: 05 Projections & Builder

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["04 Pitcher Adjustments"]  # MUST match 04's name exactly
    types: [completed]
    branches: [main]

permissions:
  contents: write

jobs:
  projections_builder:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Banner
        run: |
          echo "05 START $(TZ=America/New_York date)"
          echo "event_name=${{ github.event_name }}"
          echo "ref_name=${{ github.ref_name }}"
          echo "triggered_by=${{ github.event.workflow_run.name || 'manual' }}"
          echo "conclusion=${{ github.event.workflow_run.conclusion || 'manual' }}"

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-py-

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stage with unified logs
        shell: bash
        run: |
          set +e
          mkdir -p summaries/projections
          STATUS="summaries/projections/status.txt"
          LOG="summaries/projections/log.txt"
          ERR="summaries/projections/errors.txt"
          SUM="summaries/projections/summary.txt"
          : >"$STATUS"; : >"$LOG"; : >"$ERR"; : >"$SUM"

          ts(){ TZ="America/New_York" date +"%Y-%m-%d %I:%M:%S %p %Z"; }
          run_step(){
            echo "▶️ START: $1 ($(ts))" >>"$LOG"
            shift
            "$@" >>"$LOG" 2>step.err
            rc=$?
            if [ $rc -eq 0 ]; then
              echo "✅ $1 succeeded [$(ts)]" >>"$STATUS"
            else
              echo "❌ $1 failed [$(ts)]" >>"$STATUS"
              {
                echo "❌ $1 ERROR [$(ts)]:"
                cat step.err
                echo
                echo '---'
                echo
              } >>"$ERR"
            fi
            rm -f step.err
            echo "⏹️ END: $1 ($(ts))" >>"$LOG"
            echo >>"$LOG"
          }

          # --- Projections & Builder ---
          run_step project_prep.py                  python scripts/project_prep.py
          run_step fix_missing_batter_stats.py      python scripts/fix_missing_batter_stats.py
          run_step normalize_batters_for_builder.py python scripts/normalize_batters_for_builder.py
          run_step align_weather_team_keys.py       python scripts/align_weather_team_keys.py
          run_step project_batter_props.py          python scripts/project_batter_props.py
          run_step project_pitcher_props.py         python scripts/project_pitcher_props.py
          run_step build_expanded_batter_props.py   python scripts/build_expanded_batter_props.py
          run_step pitcher_mega_z.py                python scripts/pitcher_mega_z.py
          run_step project_final_score.py           python scripts/project_final_score.py

          {
            echo "===== RUN TIMESTAMP: $(ts) ====="
            echo
            echo "===== STATUS =====";  cat "$STATUS"
            echo; echo "===== LOG =====";   cat "$LOG"
            echo; echo "===== ERRORS =====";cat "$ERR"
          } > "$SUM"

      - name: Commit stage outputs
        run: |
          git add data/_projections/*.csv || true
          git add summaries/projections/* || true
          git diff --cached --quiet || git commit -m "05 projections & builder outputs"
          git pull --rebase origin main || true
          git push origin HEAD:main || true
