name: 06 Projection and Builder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # daily at 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history, pinned branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 0) Generate “fixed” projections
      - name: Run fix_outputs_generate_fixed_files.py
        run: python scripts/fix_outputs_generate_fixed_files.py

      # 1) Normalize all 06 inputs (force IDs to strings)
      - name: Run normalize_inputs_for_06.py
        run: python scripts/normalize_inputs_for_06.py

      # 1a) Verify required inputs exist (fail fast if missing)
      - name: Verify inputs for project_prep.py
        run: |
          set -e
          test -f data/_projections/todaysgames_normalized_fixed.csv || { echo "Missing: data/_projections/todaysgames_normalized_fixed.csv"; exit 1; }
          test -f data/Data/pitchers.csv || { echo "Missing: data/Data/pitchers.csv"; exit 1; }
          test -f data/manual/stadium_master.csv || { echo "Missing: data/manual/stadium_master.csv"; exit 1; }

      # 1b) Fingerprint project_prep.py so logs prove which version ran
      - name: Fingerprint project_prep.py
        run: |
          echo "[project_prep] PATH=scripts/project_prep.py"
          md5sum scripts/project_prep.py || shasum scripts/project_prep.py
          echo "[project_prep] HEAD (first 25 lines):"
          head -n 25 scripts/project_prep.py

      # 2) Proceed with the rest of the pipeline
      - name: Run project_prep.py
        run: python scripts/project_prep.py

      - name: Run fix_missing_batter_stats.py
        run: python scripts/fix_missing_batter_stats.py

      - name: Run normalize_batters_for_builder.py
        run: python scripts/normalize_batters_for_builder.py

      - name: Run project_batter_props.py
        run: python scripts/project_batter_props.py

      - name: Run project_pitcher_props.py
        run: python scripts/project_pitcher_props.py

      - name: Run build_expanded_batter_props.py
        run: python scripts/build_expanded_batter_props.py

      - name: Run pitcher_mega_z.py
        run: python scripts/pitcher_mega_z.py

      - name: Run starter_coverage_guard.py
        run: python scripts/starter_coverage_guard.py

      - name: Run post_normalize_pitchers.py
        run: python scripts/post_normalize_pitchers.py

      - name: Run finalize_projections.py
        run: python scripts/finalize_projections.py

      - name: Run clean_inject_team_ids.py
        run: python scripts/clean_inject_team_ids.py

      - name: Run inject_game_ids_from_schedule.py
        run: python scripts/inject_game_ids_from_schedule.py

      - name: Run inject_batter_woba_adjustments.py
        run: python scripts/inject_batter_woba_adjustments.py

      - name: Run clean_pitcher_files.py
        run: python scripts/clean_pitcher_files.py

      - name: Run impute_missing_batter_adj_woba.py
        run: python scripts/impute_missing_batter_adj_woba.py

      - name: Always write & push summary
        if: always()
        run: |
          mkdir -p summaries/06_projection
          echo "===== RUN TIMESTAMP: $(date) =====" >> summaries/06_projection/summary.txt
          echo "" >> summaries/06_projection/summary.txt
          echo "===== STATUS =====" >> summaries/06_projection/summary.txt
          cat summaries/projections/status.txt >> summaries/06_projection/summary.txt || true
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add summaries/06_projection/summary.txt
          git commit -m "Update summary log [skip ci]" || echo "No changes to commit"
          git push
