name: 06 Projection and Builder

on:
  workflow_dispatch:   # manual only

permissions:
  contents: write      # allow pushes from GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history, pinned branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Start clean: remove any previous run's summaries and recreate folder
      - name: Reset summaries directory
        run: |
          rm -rf summaries/06_projection
          mkdir -p summaries/06_projection

      # Run pipeline with fresh logs & status
      - name: Run pipeline (with logging and status)
        run: |
          set -euo pipefail
          STATUS="summaries/06_projection/status.txt"
          : > "$STATUS"

          run_py () {
            local file="$1"
            local name="$(basename "$file")"
            local ts="$(date '+%Y-%m-%d %H:%M:%S %Z')"
            local log="summaries/06_projection/${name}.log"

            # new file per run; no cross-run append because directory was reset
            echo ">> START: ${name} (${ts})" | tee "$log"
            set +e
            python "scripts/${name}" |& tee -a "$log"
            code=${PIPESTATUS[0]}
            set -e

            if [ $code -eq 0 ]; then
              echo "[OK] ${name} succeeded [${ts}]" >> "$STATUS"
            else
              echo "[FAIL] ${name} failed [${ts}]" >> "$STATUS"
            fi
            echo "[END] ${name} (${ts})" | tee -a "$log"
            return $code
          }

          # Pipeline
          run_py fix_outputs_generate_fixed_files.py || true
          run_py normalize_inputs_for_06.py || true
          run_py project_prep.py || true
          run_py fix_missing_batter_stats.py || true
          run_py normalize_batters_for_builder.py || true
          run_py project_batter_props.py || true
          run_py project_pitcher_props.py || true
          run_py build_expanded_batter_props.py || true
          run_py pitcher_mega_z.py || true
          run_py starter_coverage_guard.py || true
          run_py post_normalize_pitchers.py || true
          run_py finalize_projections.py || true
          run_py clean_inject_team_ids.py || true
          run_py inject_game_ids_from_schedule.py || true
          run_py inject_batter_woba_adjustments.py || true
          run_py clean_pitcher_files.py || true
          run_py impute_missing_batter_adj_woba.py || true
          run_py fix_missing_pa_in_pitcher_daily.py || true

      # Commit pipeline artifacts (CSV outputs + logs + status) — only fresh summaries from this run
      - name: Commit & push outputs
        if: always()
        run: |
          set -e
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          echo "=== git status (before add) ==="
          git status --porcelain || true

          git add \
            data/_projections/*.csv \
            data/end_chain/final/*.csv \
            data/raw/*.csv \
            summaries/06_projection/*.log \
            summaries/06_projection/status.txt 2>/dev/null || true

          echo "=== git status (after add) ==="
          git status --porcelain || true

          git commit -m "06 Projection: commit generated outputs and logs" || echo "No changes to commit"
          git push || echo "No changes to push"

      # Write a clean summary file (overwrites each run)
      - name: Write deep summary (overwrite)
        if: always()
        run: |
          set -euo pipefail
          SUMMARY="summaries/06_projection/summary.txt"
          STATUS="summaries/06_projection/status.txt"

          {
            echo "===== RUN TIMESTAMP: $(date) ====="
            echo
            echo "===== STATUS (per script) ====="
            if [ -s "$STATUS" ]; then
              cat "$STATUS"
            else
              echo "(status.txt not generated)"
            fi
            echo
            echo "===== FAILURES: LAST 80 LINES OF EACH FAILED SCRIPT LOG ====="
            if [ -s "$STATUS" ]; then
              awk '/^\[FAIL\]/{print $2}' "$STATUS" | sort -u | while read -r fname; do
                LOG="summaries/06_projection/${fname}.log"
                echo "---- ${fname} ----"
                if [ -f "$LOG" ]; then
                  tail -n 80 "$LOG"
                else
                  echo "(no log at $LOG)"
                fi
                echo
              done
            else
              echo "(no failures recorded)"
            fi
            echo
            echo "===== LOGS: LAST 20 LINES OF ALL SCRIPT LOGS ====="
            for LOG in summaries/06_projection/*.log; do
              [ -f "$LOG" ] || continue
              echo "---- $(basename "$LOG") ----"
              tail -n 20 "$LOG"
              echo
            done
          } > "$SUMMARY"

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "$SUMMARY"
          git commit -m "06 Projection: overwrite summary.txt [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"

      # Also publish a succinct run summary to the Actions job summary UI
      - name: Publish job summary
        if: always()
        run: |
          STATUS="summaries/06_projection/status.txt"
          echo "## 06 Projection and Builder — Run Summary" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "**Timestamp:** \`$(date)\`" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          if [ -s "$STATUS" ]; then
            echo "### Script Status" >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            # Render status lines as a code block for readability
            {
              echo '```'
              cat "$STATUS"
              echo '```'
            } >> "$GITHUB_STEP_SUMMARY"
          else
            echo "_No status produced._" >> "$GITHUB_STEP_SUMMARY"
          fi
