name: 06 Projection and Builder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"   # runs daily at 12:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          echo "===== RUN TIMESTAMP: $(date) =====" > summaries/run_log.txt
          echo "" >> summaries/run_log.txt

          python scripts/fix_outputs_generate_fixed_files.py        >> summaries/run_log.txt 2>&1 || true
          python scripts/apply_fixed_todaysgames.py                 >> summaries/run_log.txt 2>&1 || true
          python scripts/project_prep.py                            >> summaries/run_log.txt 2>&1 || true
          python scripts/fix_missing_batter_stats.py                >> summaries/run_log.txt 2>&1 || true
          python scripts/normalize_batters_for_builder.py           >> summaries/run_log.txt 2>&1 || true
          python scripts/project_batter_props.py                    >> summaries/run_log.txt 2>&1 || true
          python scripts/project_pitcher_props.py                   >> summaries/run_log.txt 2>&1 || true
          python scripts/build_expanded_batter_props.py             >> summaries/run_log.txt 2>&1 || true
          python scripts/pitcher_mega_z.py                          >> summaries/run_log.txt 2>&1 || true
          python scripts/starter_coverage_guard.py                  >> summaries/run_log.txt 2>&1 || true
          python scripts/post_normalize_pitchers.py                 >> summaries/run_log.txt 2>&1 || true
          python scripts/finalize_projections.py                    >> summaries/run_log.txt 2>&1 || true
          python scripts/clean_inject_team_ids.py                   >> summaries/run_log.txt 2>&1 || true
          python scripts/inject_game_ids_from_schedule.py           >> summaries/run_log.txt 2>&1 || true
          python scripts/inject_batter_woba_adjustments.py          >> summaries/run_log.txt 2>&1 || true
          python scripts/clean_pitcher_files.py                     >> summaries/run_log.txt 2>&1 || true
          python scripts/impute_missing_batter_adj_woba.py          >> summaries/run_log.txt 2>&1 || true
          python scripts/fix_missing_pa_in_pitcher_daily.py         >> summaries/run_log.txt 2>&1 || true

      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/_projections/*.csv data/end_chain/final/*.csv summaries/*.txt summaries/**/*.csv || true
          git commit -m "Auto-update projections and cleaned pitcher files [skip ci]" || echo "No changes to commit"
          git push
