name: 07_final_projections

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-final-projections:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || true
          fi

      - name: Run game score projection
        id: run_scores
        continue-on-error: true
        run: |
          echo "Running scripts/project_game_scores.py"
          START_TS="$(date +"%Y-%m-%d %I:%M:%S %p %Z")"
          if [ -f scripts/project_game_scores.py ]; then
            echo "▶️ START: project_game_scores.py (${START_TS})"
            python scripts/project_game_scores.py 2>&1 | tee run.log
            END_TS="$(date +"%Y-%m-%d %I:%M:%S %p %Z")"
            echo "⏹️ END: project_game_scores.py (${END_TS})" | tee -a run.log
          else
            echo "ERROR: scripts/project_game_scores.py not found" | tee run.log
            exit 1
          fi

      - name: Upload CSV (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: game_score_projections
          path: data/end_chain/final/game_score_projections.csv
          if-no-files-found: warn

      - name: Commit CSV to repo (if changed)
        if: always()
        run: |
          FILE="data/end_chain/final/game_score_projections.csv"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f "$FILE" ]; then
            git add "$FILE" || true
            if ! git diff --cached --quiet; then
              git commit -m "CI: update game score projections (${GITHUB_RUN_ID})"
              git push
              echo "Committed and pushed $FILE"
            else
              echo "No changes to commit."
            fi
          else
            echo "Output CSV not found; nothing to commit."
          fi

      - name: Write summary + error log to /summaries/07_final (always)
        if: always()
        run: |
          mkdir -p summaries/07_final

          SUMMARY_FILE="summaries/07_final/summary_${GITHUB_RUN_ID}.log"
          ERROR_FILE="summaries/07_final/errors_${GITHUB_RUN_ID}.log"

          RUN_TS="$(date +"%Y-%m-%d %I:%M:%S %p %Z")"
          STATUS_ICON="✅"
          if [ "${{ steps.run_scores.outcome }}" != "success" ]; then
            STATUS_ICON="❌"
          fi

          {
            echo "===== RUN TIMESTAMP: ${RUN_TS} ====="
            echo
            echo "===== STATUS ====="
            echo "${STATUS_ICON} project_game_scores.py ${{ steps.run_scores.outcome }} $(printf '[%s' "$(date +"%Y-%m-%d %I:%M:%S %p %Z")"); echo ']' )"
            echo
            echo "===== LOG ====="
            # Mirror the structured START/END lines and script output
            if [ -f run.log ]; then
              cat run.log
            else
              echo "No run.log captured."
            fi
            echo
            echo
            echo "===== ERRORS ====="
            if [ -f run.log ]; then
              # Grep common error keywords; if none, leave section present but empty.
              ERR_LINES="$(grep -i -E 'error|traceback|exception|failed' run.log || true)"
              if [ -n "$ERR_LINES" ]; then
                echo "$ERR_LINES"
              fi
            else
              echo "No run.log captured."
            fi
          } > "$SUMMARY_FILE"

          # Error log file is the raw run.log (or a placeholder)
          if [ -f run.log ]; then
            cp run.log "$ERROR_FILE" || true
          else
            echo "No run.log captured." > "$ERROR_FILE"
          fi

          # Commit summary + errors
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add summaries/07_final/ || true
          if ! git diff --cached --quiet; then
            git commit -m "CI: summaries/07_final for run ${GITHUB_RUN_ID}"
            git push
          fi
