name: 07_final_projections

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "15 11 * * *"  # 11:15 UTC (7:15 AM ET) – enable if you want daily runs

permissions:
  contents: write

jobs:
  run-final-projections:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          mkdir -p summaries/07_final data/_projections data/end_chain/final

      - name: Clean stale 07 logs
        run: |
          set -euo pipefail
          mkdir -p summaries/07_final
          find summaries/07_final -maxdepth 1 -type f -name "*errors*.txt" -delete || true
          find summaries/07_final -maxdepth 1 -type f -name "*status*.txt" -delete || true
          : > summaries/07_final/summary.txt

      # ---------- Stage: PREP (inject team_id & game_id into batter *_final.csv) ----------
      - name: Prep daily projection inputs
        run: |
          set -euo pipefail
          python scripts/prepare_daily_projection_inputs.py | tee -a summaries/07_final/prep_daily_log.txt

      # ---------- Stage: BATTER EVENTS ----------
      - name: Batter event probabilities
        run: |
          set -euo pipefail
          python scripts/project_batter_event_probabilities.py | tee -a summaries/07_final/batter_log.txt

      # ---------- Stage: PITCHER EVENTS ----------
      - name: Pitcher event probabilities
        run: |
          set -euo pipefail
          python scripts/project_pitcher_event_probabilities.py | tee -a summaries/07_final/pitcher_log.txt

      # ---------- Stage: GAME SCORES ----------
      - name: Game score projections
        run: |
          set -euo pipefail
          python scripts/project_game_scores.py | tee -a summaries/07_final/game_scores_log.txt

      # ---------- Sanity checks & summary ----------
      - name: Summarize run
        run: |
          set -euo pipefail
          echo "===== RUN TIMESTAMP: $(date '+%Y-%m-%d %H:%M:%S %Z') =====" > summaries/07_final/summary.txt
          echo "" >> summaries/07_final/summary.txt
          echo "===== LOG TAILS =====" >> summaries/07_final/summary.txt
          for f in prep_daily_log.txt batter_log.txt pitcher_log.txt game_scores_log.txt; do
            echo "--- ${f%.*} (tail) ---" >> summaries/07_final/summary.txt
            if [ -f "summaries/07_final/$f" ]; then
              tail -n 25 "summaries/07_final/$f" >> summaries/07_final/summary.txt
            else
              echo "(missing)" >> summaries/07_final/summary.txt
            fi
            echo "" >> summaries/07_final/summary.txt
          done

          echo "===== ERROR GREP (from current logs) =====" >> summaries/07_final/summary.txt
          # Treat 'bad_games' as a WARNING (do not fail the job for dropped/partial games)
          if grep -RniE "error|fail|assert|missing game_id|Slate mismatch|Duplicate .*pairs" summaries/07_final | grep -v summary.txt; then
            echo "(errors found)" >> summaries/07_final/summary.txt
            exit 1
          else
            echo "(no fatal errors found by grep)" >> summaries/07_final/summary.txt
          fi

          # If bad_games present, append a warning but do not fail
          if grep -Rni "bad_games" summaries/07_final | grep -v summary.txt >/dev/null 2>&1; then
            echo "(warning: bad_games present; incomplete games were dropped)" >> summaries/07_final/summary.txt
          fi

      # ---------- Commit results ----------
      - name: Commit CSVs + summaries
        if: always()
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/end_chain/final/game_score_projections.csv 2>/dev/null || true
          git add data/end_chain/final/batter_event_probabilities.csv 2>/dev/null || true
          git add data/end_chain/final/pitcher_event_probabilities.csv 2>/dev/null || true
          git add data/_projections/batter_event_probabilities.csv 2>/dev/null || true
          git add data/_projections/pitcher_event_probabilities.csv 2>/dev/null || true
          git add data/_projections/batter_props_projected_final.csv 2>/dev/null || true
          git add data/_projections/batter_props_expanded_final.csv 2>/dev/null || true
          git add summaries/07_final/* 2>/dev/null || true

          if ! git diff --cached --quiet; then
            git commit -m "CI: update final projections and summaries/07_final [$(date -u +'%Y-%m-%dT%H:%M:%SZ')]"
            git push
          else
            echo "No changes to commit."
          fi
