name: 07_final_projections

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-final-projections:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || true
          fi

      - name: Run game score projection
        id: run_scores
        continue-on-error: true
        run: |
          echo "Running scripts/project_game_scores.py"
          if [ -f scripts/project_game_scores.py ]; then
            python scripts/project_game_scores.py | tee run.log
          else
            echo "ERROR: scripts/project_game_scores.py not found" | tee run.log
            exit 1
          fi

      - name: Upload CSV (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: game_score_projections
          path: data/end_chain/final/game_score_projections.csv
          if-no-files-found: warn

      - name: Commit CSV to repo (if changed)
        if: always()
        run: |
          FILE="data/end_chain/final/game_score_projections.csv"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f "$FILE" ]; then
            git add "$FILE" || true
            if ! git diff --cached --quiet; then
              git commit -m "CI: update game score projections (${GITHUB_RUN_ID})"
              git push
              echo "Committed and pushed $FILE"
            else
              echo "No changes to commit."
            fi
          else
            echo "Output CSV not found; nothing to commit."

      - name: Always write summary
        if: always()
        run: |
          mkdir -p summaries/07_final
          SUMMARY_FILE="summaries/07_final/summary_${GITHUB_RUN_ID}.md"
          LOG_FILE="summaries/07_final/errorlog_${GITHUB_RUN_ID}.log"

          echo "# 07_final_projections" >> "$SUMMARY_FILE"
          echo "- Run ID: \`$GITHUB_RUN_ID\`" >> "$SUMMARY_FILE"
          echo "- Script: \`scripts/project_game_scores.py\`" >> "$SUMMARY_FILE"
          echo "- Step outcome: **${{ steps.run_scores.outcome }}**" >> "$SUMMARY_FILE"
          echo "" >> "$SUMMARY_FILE"

          FILE="data/end_chain/final/game_score_projections.csv"
          if [ -f "$FILE" ]; then
            ROWS=$(wc -l < "$FILE")
            echo "## Output" >> "$SUMMARY_FILE"
            echo "- File: \`$FILE\`" >> "$SUMMARY_FILE"
            echo "- Rows (incl. header): **$ROWS**" >> "$SUMMARY_FILE"
            echo "" >> "$SUMMARY_FILE"
            echo "### Preview (first 10)" >> "$SUMMARY_FILE"
            echo '```csv' >> "$SUMMARY_FILE"
            head -n 10 "$FILE" >> "$SUMMARY_FILE" || true
            echo '```' >> "$SUMMARY_FILE"
          else
            echo "## Output" >> "$SUMMARY_FILE"
            echo "- File not found: \`$FILE\`" >> "$SUMMARY_FILE"
          fi
          echo "" >> "$SUMMARY_FILE"
          echo "## Tail of run.log" >> "$SUMMARY_FILE"
          echo '```' >> "$SUMMARY_FILE"
          if [ -f run.log ]; then
            tail -n 100 run.log >> "$SUMMARY_FILE" || true
            cp run.log "$LOG_FILE" || true
          else
            echo "No run.log captured." >> "$SUMMARY_FILE"
            echo "No run.log captured." >> "$LOG_FILE"
          fi
          echo '```' >> "$SUMMARY_FILE"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add summaries/07_final/ || true
          if ! git diff --cached --quiet; then
            git commit -m "CI: update summaries 07_final (${GITHUB_RUN_ID})"
            git push
          fi
