name: 07_final_projections

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-final-projections:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          mkdir -p summaries/07_final

      # Clean stale error/status files so grep doesn't pick up old failures
      - name: Clean stale 07 logs
        run: |
          set -euo pipefail
          mkdir -p summaries/07_final
          find summaries/07_final -maxdepth 1 -type f -name "*errors*.txt" -delete || true
          find summaries/07_final -maxdepth 1 -type f -name "batter_event_probs_errors.txt" -delete || true
          find summaries/07_final -maxdepth 1 -type f -name "status.txt" -delete || true

      # 1) Prepare inputs (adds team_id and game_id to batter files)
      - name: Prepare daily inputs (inject team_id + game_id)
        run: |
          set -euo pipefail
          echo "START PREP $(date '+%Y-%m-%d %H:%M:%S %Z')" | tee summaries/07_final/prep_daily_log.txt
          python scripts/prepare_daily_projection_inputs.py 2>&1 | tee -a summaries/07_final/prep_daily_log.txt

      # 2) Build daily projections (separate steps for clear failure surface)
      - name: Build daily batter event projections
        run: |
          set -euo pipefail
          echo "START BATTERS $(date '+%Y-%m-%d %H:%M:%S %Z')" | tee summaries/07_final/batter_log.txt
          python scripts/project_batter_event_probabilities.py 2>&1 | tee -a summaries/07_final/batter_log.txt

      - name: Build daily pitcher event projections
        run: |
          set -euo pipefail
          echo "START PITCHERS $(date '+%Y-%m-%d %H:%M:%S %Z')" | tee summaries/07_final/pitcher_log.txt
          python scripts/project_pitcher_event_probabilities.py 2>&1 | tee -a summaries/07_final/pitcher_log.txt

      - name: Build game score projections
        run: |
          set -euo pipefail
          echo "START GAME SCORES $(date '+%Y-%m-%d %H:%M:%S %Z')" | tee summaries/07_final/game_scores_log.txt
          python scripts/project_game_scores.py 2>&1 | tee -a summaries/07_final/game_scores_log.txt

      # 3) Summarize (no conditionals; tolerate missing files)
      - name: Summarize run log
        if: always()
        run: |
          set -euo pipefail
          RUN_TS="$(date '+%Y-%m-%d %H:%M:%S %Z')"
          {
            echo "===== RUN TIMESTAMP: ${RUN_TS} ====="
            echo
            echo "===== LOG TAILS ====="
            echo "--- PREP (tail) ---"
            tail -n 200 summaries/07_final/prep_daily_log.txt 2>/dev/null || echo "(missing)"
            echo
            echo "--- BATTERS (tail) ---"
            tail -n 200 summaries/07_final/batter_log.txt 2>/dev/null || echo "(missing)"
            echo
            echo "--- PITCHERS (tail) ---"
            tail -n 200 summaries/07_final/pitcher_log.txt 2>/dev/null || echo "(missing)"
            echo
            echo "--- GAME SCORES (tail) ---"
            tail -n 200 summaries/07_final/game_scores_log.txt 2>/dev/null || echo "(missing)"
            echo
            echo "===== ERROR GREP (from current logs) ====="
            grep -i -E 'error|traceback|exception' summaries/07_final/*log.txt 2>/dev/null || echo "(no errors found by grep)"
          } > summaries/07_final/summary.txt

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: game_score_projections
          path: |
            data/end_chain/final/game_score_projections.csv
            data/end_chain/final/batter_event_probabilities.csv
            data/end_chain/final/pitcher_event_probabilities.csv
            summaries/07_final/*.txt
            summaries/07_final/*.csv
          if-no-files-found: warn
          retention-days: 7

      - name: Commit outputs and summaries
        if: always()
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/end_chain/final/game_score_projections.csv 2>/dev/null || true
          git add data/end_chain/final/batter_event_probabilities.csv 2>/dev/null || true
          git add data/end_chain/final/pitcher_event_probabilities.csv 2>/dev/null || true
          git add summaries/07_final/* 2>/dev/null || true
          if ! git diff --cached --quiet; then
            git commit -m "CI: update final projections and summaries/07_final"
            git push
          else
            echo "No changes to commit."
          fi
