name: 07_final_projections

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-final-projections:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || true
          fi

      - name: Run game score projection
        id: run_scores
        continue-on-error: true
        run: |
          echo "Running scripts/project_game_scores.py"
          if [ -f scripts/project_game_scores.py ]; then
            python scripts/project_game_scores.py | tee run.log
          else
            echo "ERROR: scripts/project_game_scores.py not found" | tee run.log
            exit 1
          fi

      - name: Upload CSV (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: game_score_projections
          path: data/end_chain/final/game_score_projections.csv
          if-no-files-found: warn

      - name: Commit CSV to repo (if changed)
        if: always()
        run: |
          FILE="data/end_chain/final/game_score_projections.csv"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f "$FILE" ]; then
            git add "$FILE" || true
            if ! git diff --cached --quiet; then
              git commit -m "CI: update game score projections (${GITHUB_RUN_ID})"
              git push
              echo "Committed and pushed $FILE"
            else
              echo "No changes to commit."
            fi
          else
            echo "Output CSV not found; nothing to commit."
          fi

      - name: Always write summary and error log to /summaries/07_final
        if: always()
        run: |
          mkdir -p summaries/07_final
          SUMMARY_FILE="summaries/07_final/summary_${GITHUB_RUN_ID}.md"
          ERROR_FILE="summaries/07_final/errorlog_${GITHUB_RUN_ID}.log"

          {
            echo "# 07_final_projections"
            echo "- Run ID: \`$GITHUB_RUN_ID\`"
            echo "- Script: \`scripts/project_game_scores.py\`"
            echo "- Step outcome: **${{ steps.run_scores.outcome }}**"
            echo
            FILE="data/end_chain/final/game_score_projections.csv"
            if [ -f "$FILE" ]; then
              ROWS=$(wc -l < "$FILE")
              echo "## Output"
              echo "- File: \`$FILE\`"
              echo "- Rows (incl. header): **$ROWS**"
              echo
              echo "### Preview (first 10)"
              echo '```csv'
              head -n 10 "$FILE" || true
              echo '```'
            else
              echo "## Output"
              echo "- File not found: \`$FILE\`"
            fi
            echo
            echo "## Tail of run.log"
            echo '```'
            if [ -f run.log ]; then
              tail -n 200 run.log || true
            else
              echo "No run.log captured."
            fi
            echo '```'
          } >> "$SUMMARY_FILE"

          if [ -f run.log ]; then
            cp run.log "$ERROR_FILE" || true
          else
            echo "No run.log captured." > "$ERROR_FILE"
          fi

          # Also mirror key details to the GitHub job summary
          {
            echo "# 07_final_projections"
            echo "- Run ID: \`$GITHUB_RUN_ID\`"
            echo "- Step outcome: **${{ steps.run_scores.outcome }}**"
            echo
            echo "Summary and error log saved to \`summaries/07_final/\` and committed."
          } >> "$GITHUB_STEP_SUMMARY"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add summaries/07_final/ || true
          if ! git diff --cached --quiet; then
            git commit -m "CI: add summaries/07_final for run ${GITHUB_RUN_ID}"
            git push
          fi
