name: 07_final_projections

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-final-projections:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || true
          fi

      - name: Run game score projection
        run: |
          python scripts/project_game_scores.py 2>&1 | tee run.log

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: game_score_projections
          path: |
            data/end_chain/final/game_score_projections.csv
            summaries/07_final/*.txt
          if-no-files-found: warn

      - name: Commit results
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/end_chain/final/game_score_projections.csv || true
          git add summaries/07_final/*.txt || true
          if ! git diff --cached --quiet; then
            git commit -m "CI: update game_score_projections and summaries/07_final"
            git push
          fi
