name: 07_final_projections

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-final-projections:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || true
          fi

      - name: Prepare inputs (scripts/final_csvs_prep.py)
        id: prep_inputs
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p summaries/07_final
          echo "START PREP $(date '+%Y-%m-%d %H:%M:%S %Z')" | tee summaries/07_final/prep_log.txt
          python scripts/final_csvs_prep.py 2>&1 | tee -a summaries/07_final/prep_log.txt

      - name: Run projections (capture log, never swallow failures)
        id: run_scores
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p summaries/07_final
          echo "START $(date '+%Y-%m-%d %H:%M:%S %Z')" | tee run.log
          python scripts/project_game_scores.py 2>&1 | tee -a run.log

      - name: Summarize run log
        if: always()
        shell: bash
        run: |
          mkdir -p summaries/07_final
          RUN_TS="$(date '+%Y-%m-%d %H:%M:%S %Z')"

          if [ -f run.log ]; then
            cp run.log summaries/07_final/log.txt
          else
            echo "no run.log" > summaries/07_final/log.txt
          fi

          STATUS_ICON="OK"
          if [ "${{ steps.run_scores.outcome }}" != "success" ]; then
            STATUS_ICON="FAIL"
          fi
          echo "${STATUS_ICON} project_game_scores.py [${RUN_TS}]" > summaries/07_final/status.txt

          if [ -f summaries/07_final/log.txt ]; then
            (grep -i -E 'error|traceback|exception' summaries/07_final/log.txt || true) > summaries/07_final/errors.txt
          else:
            echo "no log" > summaries/07_final/errors.txt
          fi

          {
            echo "===== RUN TIMESTAMP: ${RUN_TS} ====="
            echo
            echo "===== STATUS ====="
            cat summaries/07_final/status.txt
            echo
            echo "===== PREP LOG (tail) ====="
            tail -n 200 summaries/07_final/prep_log.txt || true
            echo
            echo "===== LOG (tail) ====="
            tail -n 200 summaries/07_final/log.txt || true
            echo
            echo "===== ERRORS ====="
            cat summaries/07_final/errors.txt
            echo
            echo "===== DIAGNOSTIC CSVs (if any) ====="
            ls -1 summaries/07_final/*.csv 2>/dev/null || echo "none"
          } > summaries/07_final/summary.txt

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: game_score_projections
          path: |
            data/end_chain/final/game_score_projections.csv
            summaries/07_final/prep_log.txt
            summaries/07_final/log.txt
            summaries/07_final/status.txt
            summaries/07_final/errors.txt
            summaries/07_final/summary.txt
            summaries/07_final/*.csv
          if-no-files-found: warn
          retention-days: 7

      - name: Commit outputs and summaries
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/end_chain/final/game_score_projections.csv || true
          git add summaries/07_final/* || true
          if ! git diff --cached --quiet; then
            git commit -m "CI: update final projections and summaries/07_final (including diagnostics)"
            git push
          else
            echo "No changes to commit."
          fi
