name: Activate 3

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  activate_3:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run All Scripts + Generate Logs
        run: |
          mkdir -p summaries/Activate3

          run_step() {
            SCRIPT="$1"
            STEP_NAME=$(basename "$SCRIPT" .py)
            LOG="summaries/Activate3/${STEP_NAME}.log"
            TXT="summaries/Activate3/${STEP_NAME}.txt"

            if python "scripts/${SCRIPT}" > "$LOG" 2>&1; then
              echo "✅ ${SCRIPT} ran successfully." > "$TXT"
            else
              echo "❌ ${SCRIPT} encountered an error." > "$TXT"
            fi
          }

          run_step update_game_time.py
          run_step split_batters_by_home_away.py
          run_step split_pitchers.py
          run_step generate_weather_csv.py
          run_step filter_today_batters.py
          run_step get_weather_data.py

          # Final summary
          TS=$(TZ="America/New_York" date +"%Y-%m-%d %I:%M:%S %p %Z")
          {
            echo "✅ Activate 3 Summary — $TS"
            for FILE in summaries/Activate3/*.txt; do
              echo "$(basename "$FILE")"
            done
          } > summaries/Activate3/activate_3.txt

      - name: Commit Summary Logs + Weather Output
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -f summaries/Activate3/*.txt summaries/Activate3/*.log data/weather_adjustments.csv || true
          git diff --cached --quiet || git commit -m "Activate 3: full summary logs committed"
          git push || echo "Nothing to push"
