name: Activate 3

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  activate_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas requests pytz

      - name: Run All Scripts + Generate Logs
        run: |
          mkdir -p summaries/Activate3

          declare -A scripts=(
            ["update_game_time"]="scripts/update_game_time.py"
            ["generate_weather_csv"]="scripts/generate_weather_csv.py"
            ["get_weather_data"]="scripts/get_weather_data.py"
            ["filter_today_batters"]="scripts/filter_today_batters.py"
            ["split_batters_by_home_away"]="scripts/split_batters_by_home_away.py"
            ["split_pitchers"]="scripts/split_pitchers.py"
          )

          for key in "${!scripts[@]}"; do
            LOG="summaries/Activate3/${key}.log"
            TXT="summaries/Activate3/${key}.txt"
            PY=${scripts[$key]}

            echo "▶ Running $PY"
            if python "$PY" > "$LOG" 2>&1; then
              echo "✅ $PY ran successfully." > "$TXT"
            else
              echo "❌ $PY encountered an error." > "$TXT"
            fi

            # Always touch to ensure git sees the file
            touch "$LOG"
            touch "$TXT"
          done

          # Final Summary
          ET_TIMESTAMP=$(TZ="America/New_York" date +"%Y-%m-%d %I:%M:%S %p %Z")
          {
            echo "✅ Activate 3 Summary — $ET_TIMESTAMP"
            for key in "${!scripts[@]}"; do
              echo "${scripts[$key]} (summaries/Activate3/${key}.txt)"
            done
          } > summaries/Activate3/activate_3.txt

          touch summaries/Activate3/activate_3.txt

      - name: Commit Summary Logs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add summaries/Activate3/*.txt summaries/Activate3/*.log || true
          git commit -m "✅ Activate 3: full summary logs committed" || echo "No changes to commit"
          git push || echo "Nothing to push"
