name: Activate 3

on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  activate_3:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run All Scripts + Generate Logs
        run: |
          mkdir -p summaries/Activate3
          python scripts/update_game_time.py
          python scripts/split_batters_by_home_away.py
          python scripts/split_pitchers.py
          python scripts/generate_weather_csv.py
          python scripts/filter_today_batters.py
          python scripts/get_weather_data.py

      - name: Commit Summary Logs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -f summaries/Activate3/*.txt summaries/Activate3/*.log data/weather_adjustments.csv || true
          git diff --cached --quiet || git commit -m "Activate 3: full summary logs committed"
          git push || echo "Nothing to push"
