
name: Adjust Pitchers with Park and Weather

on:
  workflow_dispatch:

jobs:
  adjust-pitchers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run Pitcher Adjustment Script
        run: python scripts/adjust_pitchers_weather_park.py

      - name: Upload Adjusted Pitcher Files
        uses: actions/upload-artifact@v4
        with:
          name: adjusted-pitchers
          path: |
            data/adjusted/pitchers_adjusted_home.csv
            data/adjusted/pitchers_adjusted_away.csv
