name: Apply Park Weather Adjustment

on:
  workflow_dispatch:

jobs:
  run-adjustment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas numpy python-dateutil

      - name: Run Adjustment Script
        run: python scripts/apply_park_weather_adjustment.py

      - name: Commit adjusted files to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/adjusted/batters_adjusted_weather_park.csv
          git add data/adjusted/adjustment_log.txt
          git commit -m "Auto-commit: adjusted batters + log" || echo "No changes to commit"
          git push

      - name: Upload Adjusted File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: adjusted-batters
          path: data/adjusted/batters_adjusted_weather_park.csv