name: Apply Pitcher Park Adjustment

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas

      - name: Run pitcher park adjustment
        run: |
          echo "===== Running Python Script ====="
          python scripts/apply_pitcher_park_adjustment.py
          echo "===== Script Execution Complete ====="
          echo "===== Listing Adjusted Files ====="
          ls -lh data/adjusted/
          echo "===== Log File Preview ====="
          head -n 20 log_pitchers_home_park.txt || echo "log_pitchers_home_park.txt missing"
          head -n 20 log_pitchers_away_park.txt || echo "log_pitchers_away_park.txt missing"

      - name: Commit adjusted files to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git status
          git add data/adjusted/pitchers_*_park.csv log_pitchers_*_park.txt || true
          git commit --allow-empty -m "Auto-commit: pitcher park adjustments"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
