name: Apply Park Adjustment

on:
  workflow_dispatch:

jobs:
  apply-park-adjustment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install pandas

      - name: Run Park Factor Adjustment Script
        run: python scripts/apply_park_adjustment.py

      - name: Upload Adjusted Batters (Park)
        uses: actions/upload-artifact@v4
        with:
          name: adjusted-batters-park
          path: |
            data/adjusted/batters_home_park.csv
            data/adjusted/batters_away_park.csv
            data/adjusted/log_park_home.txt
            data/adjusted/log_park_away.txt
