name: Apply Pitcher Park Adjustment

on:
  workflow_dispatch:

jobs:
  run-adjustment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: true

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas

      - name: Run Pitcher Park Adjustment
        run: python scripts/apply_pitcher_park_adjustment.py
