name: Apply Pitcher Park Adjustment

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas

      - name: Run pitcher park adjustment
        run: python scripts/apply_pitcher_park_adjustment.py

      - name: Commit adjusted files to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/adjusted/pitchers_*_park.csv log_pitchers_*_park.txt
          git commit -m "Auto-commit: pitcher park adjustments"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
