
name: Apply Park Adjustment

on:
  workflow_dispatch:

jobs:
  apply-park-adjustment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: Run park adjustment
        run: python apply_park_adjustment.py

      - name: Commit adjusted files to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/adjusted/*
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Apply park factor adjustment"
            git push
