name: Apply Park and Weather Adjustments

on:
  workflow_dispatch:
  schedule:
    - cron: "30 10 * * *"  # Runs daily at 10:30 UTC

jobs:
  adjust-projections:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting adjustment job..."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: Run Adjustment Script
        run: python apply_weather_park_adjustments.py
