name: Apply Park Adjustment

on:
  workflow_dispatch:

jobs:
  park-adjustment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: Run Park Adjustment Script
        run: python scripts/apply_park_adjustment.py

      - name: Commit and Push Adjusted Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/adjusted/*.csv data/adjusted/*.txt
          git commit -m "Auto-commit: park-adjusted batters + log"
          git push
