name: Apply Pitcher Park Adjustment

on:
  workflow_dispatch:

jobs:
  run-adjustment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: true

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install only required package
        run: pip install unidecode

      - name: Run Pitcher Park Adjustment Script
        run: python scripts/apply_pitcher_park_adjustment.py

      - name: Commit and Push Output Files
        run: |
          git add data/adjusted/pitchers_home_park.csv
          git add data/adjusted/pitchers_away_park.csv
          git add log_pitchers_home_park.txt
          git add log_pitchers_away_park.txt
          git commit -m "Auto-update pitcher park adjustment"
          git push
