name: Apply Pitcher Weather Adjustment

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/apply_pitcher_weather_adjustment.py'
      - '.github/workflows/apply-pitcher-weather-adjustment.yml'
      - 'data/weather_adjustments.csv'
      - 'data/raw/todaysgames_normalized.csv'
      - 'data/adjusted/pitchers_home.csv'
      - 'data/adjusted/pitchers_away.csv'

jobs:
  apply-pitcher-weather-adjustment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run Pitcher Weather Adjustment Script
        run: python scripts/apply_pitcher_weather_adjustment.py
