name: Audit Workflow Python References

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
      - "audit_workflow_py_refs.py"

permissions:
  contents: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run audit script
        run: python audit_workflow_py_refs.py

      - name: Commit audit results
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add audit/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update workflow audit reports"
            git push
          fi
