name: "Audit Orphan CSVs"

on:
  workflow_dispatch:  # lets you run it manually from the Actions tab

permissions:
  contents: write

jobs:
  audit-orphans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run orphan CSV audit
        run: |
          python tools/find_orphan_csvs.py --days 30

      - name: Commit & push report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add summaries/audit/orphan_csv_report.csv || true
          git commit -m "Audit: update orphan_csv_report.csv [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
