name: Run Bet Tracker
on:
  workflow_dispatch:

jobs:
  run-bet-tracker:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install "pandas==2.2.2" requests
          fi

      - name: Git safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global pull.rebase true

      - name: Snapshot pre-run line counts
        id: counts_before
        run: |
          PLAYERS="data/bets/player_props_history.csv"
          GAMES="data/bets/game_props_history.csv"
          PLAYERS_BEFORE=$( [ -f "$PLAYERS" ] && (wc -l < "$PLAYERS") || echo 0 )
          GAMES_BEFORE=$( [ -f "$GAMES" ] && (wc -l < "$GAMES") || echo 0 )
          echo "players_before=$PLAYERS_BEFORE" >> $GITHUB_OUTPUT
          echo "games_before=$GAMES_BEFORE" >> $GITHUB_OUTPUT

      - name: Execute Bet Tracker
        run: python scripts/main.py

      - name: Snapshot post-run line counts
        id: counts_after
        run: |
          PLAYERS="data/bets/player_props_history.csv"
          GAMES="data/bets/game_props_history.csv"
          PLAYERS_AFTER=$( [ -f "$PLAYERS" ] && (wc -l < "$PLAYERS") || echo 0 )
          GAMES_AFTER=$( [ -f "$GAMES" ] && (wc -l < "$GAMES") || echo 0 )
          echo "players_after=$PLAYERS_AFTER" >> $GITHUB_OUTPUT
          echo "games_after=$GAMES_AFTER" >> $GITHUB_OUTPUT

      - name: Show deltas
        run: |
          echo "Player props: $(( ${{ steps.counts_after.outputs.players_after }} - ${{ steps.counts_before.outputs.players_before }} )) line(s) change"
          echo "Game props:   $(( ${{ steps.counts_after.outputs.games_after }}   - ${{ steps.counts_before.outputs.games_before }} )) line(s) change"

      - name: Commit and Push Changes (rebase-safe)
        shell: bash
        run: |
          set -e
          git add data/bets/player_props_history.csv data/bets/game_props_history.csv
          if [[ -z "$(git status --porcelain data/bets/player_props_history.csv data/bets/game_props_history.csv)" ]]; then
            echo "No bet-tracker changes to commit."
            exit 0
          fi
          git commit -m "Automated bet tracker update"
          BRANCH="${GITHUB_REF_NAME:-main}"
          for attempt in 1 2; do
            echo "Attempt $attempt: syncing with origin/$BRANCH..."
            git fetch origin
            git rebase "origin/$BRANCH" || (echo "Rebase failed"; git rebase --abort; exit 1)
            if git push origin "HEAD:$BRANCH"; then
              echo "Push succeeded."
              break
            else
              echo "Push rejected (non-fast-forward). Retrying..."
              sleep 2
            fi
          done
