name: Run Bet Tracker

on:
  workflow_dispatch:

jobs:
  run-bet-tracker:
    name: Run Daily Bet Tracker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install pandas

      - name: Execute Script
        run: python bet_tracker.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add data/bets/game_props_history.csv
            git add data/bets/player_props_history.csv
            git commit -m "Automated update of bet tracker data"
            git push
          else
            echo "No changes to commit. Exiting successfully."
          fi
