# .github/workflows/bet_tracker.yml
name: Run Bet Tracker (Minimal)

on:
  workflow_dispatch:

jobs:
  run-bet-tracker:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas==2.2.2 requests
          fi

      - name: Git config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global pull.rebase true

      - name: Run bet tracker (modular)
        run: python scripts/main.py

      - name: Commit and push changes
        run: |
          git add data/bets/player_props_history.csv data/bets/game_props_history.csv || true
          if [ -z "$(git status --porcelain -- data/bets/player_props_history.csv data/bets/game_props_history.csv)" ]; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated bet tracker update"
          BRANCH="${GITHUB_REF_NAME:-main}"
          git fetch origin
          git rebase "origin/$BRANCH" || (git rebase --abort; exit 1)
          git push origin "HEAD:$BRANCH"
