name: Run Bet Tracker
on:
  workflow_dispatch:

jobs:
  run-bet-tracker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install "pandas==2.2.2" requests

      - name: Git config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Run tracker
        run: |
          set -e
          if [ -f scripts/main.py ]; then
            python -u scripts/main.py 2>&1 | tee run.log
          else
            python -u scripts/bet_tracker.py 2>&1 | tee run.log
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bet-tracker-artifacts
          path: |
            run.log
            data/bets/player_props_history.csv
            data/bets/game_props_history.csv

      - name: Commit and push CSVs
        run: |
          git add data/bets/player_props_history.csv data/bets/game_props_history.csv || true
          if [ -z "$(git status --porcelain -- data/bets/player_props_history.csv data/bets/game_props_history.csv)" ]; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Automated bet tracker update"
          git push
