name: Build Prop Candidates

on:
  workflow_dispatch:

jobs:
  build-prop-candidates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas

      - name: Run build_prop_candidates.py
        run: python scripts/build_prop_candidates.py

      - name: Commit and Push Prop Candidates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/final/prop_candidates.csv || exit 0
          git commit -m "📦 Added prop candidates CSV" || echo "No changes to commit"
          git push || echo "Nothing to push"
