name: Build Top Picks JSON

on:
  workflow_dispatch:

jobs:
  build-top-picks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: Run Top Picks Builder
        run: python scripts/build_top_picks_json.py

      - name: Commit and push top picks JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/json/top_picks.json
          git commit -m "Add top picks JSON"
          git push
