name: Build Top Props JSON

on:
  workflow_dispatch:

jobs:
  build-top-props:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install pandas

    - name: Run Top Props Builder
      run: |
        python scripts/build_top_props_json.py

    - name: Commit and push top props JSON
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data/final/top_props.json
        git commit -m "Add top props JSON output"
        git push
