name: Clean Raw Game Data

on:
  workflow_dispatch:

jobs:
  clean-game-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: Run cleanup script
        run: python scripts/clean_raw_game_data.py

      - name: Upload cleaned files
        uses: actions/upload-artifact@v4
        with:
          name: cleaned-game-data
          path: |
            data/daily/todays_pitchers.csv
            data/daily/starting_lineups.csv
