name: step16b

on:
  workflow_dispatch:

jobs:
  step16b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas requests pytz

      - name: Run combine_pitcher_weather_park_home_step2.py
        run: |
          echo "🔧 Starting combine_pitcher_weather_park_home_step2.py..."
          python scripts/combine_pitcher_weather_park_home_step2.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Step 16b: Ran combine_pitcher_weather_park_home_step2.py"
          git push || echo "No changes to commit or push"
