name: Combine Pitcher Weather Park Away

on:
  workflow_dispatch:

jobs:
  combine_pitcher_weather_park_away:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas

      - name: Run combine_pitcher_weather_park_away.py
        run: python scripts/combine_pitcher_weather_park_away.py

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: combined-pitchers-away
          path: |
            data/adjusted/pitchers_away_adjusted.csv
            data/adjusted/log_combined_pitchers_away.txt
