name: Combine Batter Weather + Park

on:
  workflow_dispatch:

jobs:
  combine-batter-weather-park:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install pandas

      - name: Run Merger
        run: python scripts/combine_batter_weather_park.py
