name: Duplicate Check After Normalization

on:
  workflow_dispatch:

jobs:
  deduplicate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pandas
        run: pip install pandas

      - name: Run deduplicate_normalized.py
        run: python deduplicate_normalized.py

      - name: Commit and push cleaned normalized files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/cleaned/*_normalized_cleaned.csv || true
          git diff --cached --quiet || git commit -m "Deduplicated normalized files"
          git push
