name: Fetch MLB Rosters

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run roster fetch script
        run: |
          python scripts/fetch_rosters.py

      - name: Normalize roster CSVs to team files
        run: |
          python scripts/normalize_rosters_to_team_csvs.py

      - name: Force commit and push updated roster CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/rosters/*.csv
          git add data/rosters/ready/*.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update MLB rosters"
          git push --force || echo "Nothing to push"
        continue-on-error: true

      - name: Prepare team CSVs
        run: |
          python scripts/team_csvs_prep.py

      - name: Force commit and push team_csvs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/team_csvs/*.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update team CSVs"
          git push --force || echo "Nothing to push"
        continue-on-error: true

      - name: Build player-team master list
        run: |
          python scripts/build_player_team_master.py

      - name: Force commit and push player_team_master
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/processed/player_team_master.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update player_team_master"
          git push --force || echo "Nothing to push"
        continue-on-error: true
