name: Build Batter Projections & Final Props

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "25 14 * * *"   # <- optional

permissions:
  contents: write

concurrency:
  group: finalprops-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-finalize:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (lightweight fallback if no requirements.txt)
        run: |
          if [[ -f requirements.txt ]]; then
            pip install -r requirements.txt
          else
            pip install --upgrade pip
            pip install pandas numpy
          fi

      - name: Show inputs for projections
        run: |
          ls -lah || true
          ls -lah data/_projections || true
          echo "Head of batter_props_z_expanded.csv (if present):"
          if [[ -f data/_projections/batter_props_z_expanded.csv ]]; then
            python - <<'PY'
import pandas as pd
p="data/_projections/batter_props_z_expanded.csv"
print(pd.read_csv(p).head(8))
PY
          fi

      - name: Snapshot pre-run hashes
        run: |
          for f in \
            data/_projections/batter_props_z_expanded.csv \
            data/_projections/batter_props_projected.csv \
            data/bets/prep/batter_props_final.csv \
            data/bets/player_props_history.csv; do
            if [[ -f "$f" ]]; then
              echo "$(sha256sum "$f")"
            fi
          done

      - name: Run project_batter_props.py (build projected probs)
        run: |
          python scripts/project_batter_props.py

      - name: Validate probability spread (projected)
        run: |
          python scripts/validate_probability_spread.py \
            --file data/_projections/batter_props_projected.csv \
            --cols prob_hits_over_1p5 prob_tb_over_1p5 prob_hr_over_0p5

      # Optional: if you have your own “final props” scoring scripts,
      # these steps will run ONLY if the files exist.
      - name: Run final_props_1.py
        if: ${{ hashFiles('scripts/final_props_1.py') != '' }}
        run: python scripts/final_props_1.py

      - name: Run final_scores_1.py
        if: ${{ hashFiles('scripts/final_scores_1.py') != '' }}
        run: python scripts/final_scores_1.py

      - name: Run final_scores_2.py (update game IDs etc.)
        if: ${{ hashFiles('scripts/final_scores_2.py') != '' }}
        run: python scripts/final_scores_2.py

      - name: Append to player props history (no clipping)
        run: |
          python scripts/append_player_history_from_prep.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: props-output
          path: |
            data/_projections/batter_props_projected.csv
            data/bets/player_props_history.csv
          if-no-files-found: ignore
          retention-days: 7

      # If you want the CSVs committed back to the repo, leave this step;
      # otherwise delete it.
      - name: Commit updated CSVs back to main
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            data/_projections/batter_props_projected.csv
            data/bets/player_props_history.csv
          message: "ci: update projected probs & history (no clipping)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
