- name: Validate probability spread (projected)
  run: |
    python - <<'PY'
    import pandas as pd, numpy as np, sys
    p = "data/_projections/batter_props_projected.csv"
    try:
      df = pd.read_csv(p)
    except Exception as e:
      print(f"Could not load {p}: {e}")
      sys.exit(1)

    cols = [c for c in df.columns if c.startswith("prob_")]
    if not cols:
      print("No probability columns to check.")
      sys.exit(0)

    flat = []
    for c in cols:
      s = pd.to_numeric(df[c], errors="coerce").dropna()
      if s.empty: 
        continue
      # "Flat" if almost all mass sits in a very tight band
      if (s.max() - s.min()) < 0.1 and (s.quantile(0.75) - s.quantile(0.25)) < 0.02:
        flat.append((c, float(s.mean()), float(s.std()), float(s.min()), float(s.max())))

    if flat:
      print("⚠️  Probabilities look flat in these columns (warning only):")
      for c, mean, std, mn, mx in flat:
        print(f" - {c}: mean={mean:.3f}, std={std:.3f}, min={mn:.3f}, max={mx:.3f}")
    else:
      print("✅ Probability spread looks reasonable.")
    # WARNING ONLY – do not fail the job
    sys.exit(0)
    PY
