name: Build Batter Projections & Props

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'  # 13:00 UTC = 9am ET

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy
          fi

      # (Optional) Show first matching input file and a few columns — no heredocs
      - name: Show inputs (optional)
        run: |
          set -euo pipefail
          for p in data/_projections/batter_props_z_expanded.csv data/batter_props_z_expanded.csv batter_props_z_expanded.csv; do
            if [ -f "$p" ]; then
              echo "Found input: $p"
              python -c "import pandas as pd; import sys; d=pd.read_csv(sys.argv[1]); print('cols:', list(d.columns)[:12], '… rows:', len(d))" "$p"
              break
            fi
          done

      - name: Run project_batter_props.py
        run: python scripts/project_batter_props.py

      # Soft validation (prints stats but never blocks the run)
      - name: Validate probability spread (projected)
        run: |
          set -euo pipefail
          f="data/_projections/batter_props_projected.csv"
          if [ -f "$f" ]; then
            echo "Stats for $f"
            python -c "import pandas as pd; import numpy as np; \
import sys; df=pd.read_csv(sys.argv[1]); \
s=df[['prob_hits_over_1p5','prob_tb_over_1p5','prob_hr_over_0p5']].stack(); \
print(s.describe())" "$f" || true
          else
            echo "Projected file not found: $f"
          fi

      - name: Commit and push changes
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update projections [skip ci]" || echo "No changes to commit"
          git push
