
name: Generate Matchup Stats

on:
  workflow_dispatch:

jobs:
  generate-matchups:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pandas
        run: pip install pandas

      - name: Run matchup generator
        run: python generate_matchup_stats.py

      - name: Commit matchup file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/matchups/matchup_stats.csv
          git commit -m "Auto-commit: matchup_stats.csv"
          git push
