name: Generate Weather Input

on:
  workflow_dispatch:

jobs:
  generate-weather-input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas

      - name: Generate weather input CSV
        run: python generate_weather_input.py