name: Merge Game and Pitcher Data

on:
  workflow_dispatch:

jobs:
  merge-game-pitcher-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pandas
      - name: Run merge_game_pitcher_data.py
        run: python scripts/merge_game_pitcher_data.py
