
name: Normalize Todays Lineups

on:
  workflow_dispatch:

jobs:
  normalize-lineups:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas

    - name: Normalize today's lineups
      run: python scripts/normalize_lineups.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add data/raw/lineups_normalized.csv
        git commit -m "Normalize lineups and save output" || echo "No changes to commit"
        git push
