name: Normalize Player Names

on:
  workflow_dispatch:

jobs:
  normalize-names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pandas
        run: pip install pandas

      - name: Run normalization script
        run: python normalize_names.py

      - name: Commit normalized files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "🧼 Normalize player name columns" || echo "Nothing to commit"
          git push || echo "Nothing to push"
