name: Normalize Batter and Pitcher Names

on:
  workflow_dispatch:

jobs:
  normalize-names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pandas
        run: pip install pandas

      - name: Run normalize_names.py
        run: python normalize_names.py

      - name: Commit and push normalized CSVs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/normalized/*.csv
          git commit -m "Normalize batter and pitcher names"
          git push