name: Pipeline Prep (00-05)

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: pipeline-prep-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  prep:
    name: 00–05 Prep (with Weather)
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      FORCE_COLOR: "1"
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libxml2-dev libxslt1-dev python3-dev build-essential

      - name: Install Python deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Git identify
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      ####################################################################
      # 00 – Foundation / Normalize / Inject Pitcher IDs / Rebuild SP ctx
      ####################################################################
      - name: 00_foundation_normalize
        run: |
          set -euo pipefail
          mkdir -p summaries/00_foundation logs data/_projections data/end_chain/final data/temp_inputs
          python scripts/todaysgames.py                                2>&1 | tee logs/00_todaysgames.log
          python scripts/normalize_todays_games.py                     2>&1 | tee logs/01_normalize_todays_games.log
          python scripts/inject_pitcher_ids_into_games.py              2>&1 | tee logs/02_inject_pitcher_ids.log
          python scripts/rebuild_startingpitchers.py                   2>&1 | tee logs/03_rebuild_startingpitchers.log

      ####################################################################
      # 01 – Split Home/Away & Stage
      ####################################################################
      - name: 01_split_and_stage
        run: |
          set -euo pipefail
          python scripts/splithome.py             2>&1 | tee logs/04_splithome.log
          python scripts/splitaway.py             2>&1 | tee logs/05_splitaway.log
          python scripts/bet_prep_1.py            2>&1 | tee logs/06_bet_prep_1.log

      ####################################################################
      # 02 – Context / Fixups (optional extras that don't affect SP IDs)
      ####################################################################
      - name: 02_context_and_fixes
        run: |
          set -euo pipefail
          if [ -f scripts/fix_team_names.py ]; then python scripts/fix_team_names.py | tee logs/07_fix_team_names.log; fi
          if [ -f scripts/park_factors.py ]; then python scripts/park_factors.py | tee logs/08_park_factors.log; fi

      ####################################################################
      # 03 – Weather Inputs (MANDATORY)
      ####################################################################
      - name: 03_weather_inputs (MANDATORY)
        run: |
          set -euo pipefail
          python scripts/weather_inputs.py 2>&1 | tee logs/09_weather_inputs.log

      ####################################################################
      # 04 – Weather Adjustments (MANDATORY)
      ####################################################################
      - name: 04_weather_adjustments_batters (MANDATORY)
        run: |
          set -euo pipefail
          python scripts/weatheradjustments_batters.py 2>&1 | tee logs/10_weather_batters.log

      - name: 04_weather_adjustments_pitchers (MANDATORY)
        run: |
          set -euo pipefail
          python scripts/weatheradjustments_pitchers.py 2>&1 | tee logs/11_weather_pitchers.log

      ####################################################################
      # 05 – Prep Summary & Commit
      ####################################################################
      - name: 05_prep_summary
        run: |
          set -euo pipefail
          mkdir -p summaries
          {
            echo "=== Pipeline Prep Summary (00-05) ==="
            echo "Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            echo
            echo "[00] Foundation/Normalize/Inject/Rebuild: OK"
            echo "[01] Split & Stage: OK"
            echo "[02] Context & Fixes: OK (see logs for conditional steps)"
            echo "[03] Weather Inputs: OK"
            echo "[04] Weather Adjustments (Batters/Pitchers): OK"
            echo
            echo "--- Key files present ---"
            ls -lah data/_projections || true
            ls -lah data/end_chain/final || true
            echo
            echo "--- Recent logs ---"
            tail -n +1 logs/*.log | sed -e 's/\x1b\[[0-9;]*m//g' | tail -n 200 || true
          } > summaries/pipeline-prep_summary.txt

      - name: Commit artifacts
        env:
          TARGET_BRANCH: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Prep: 00-05 (inject pitcher IDs before rebuild) + mandatory weather"
            git push --force-with-lease origin HEAD:${TARGET_BRANCH}
          fi
