name: Pipeline Prep (00-05)

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: pipeline-prep-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  prep:
    name: 00–05 Prep (with Weather)
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      FORCE_COLOR: "1"
      TZ: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            libxml2-dev libxslt1-dev python3-dev build-essential

      - name: Install Python deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Git identify
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      ####################################################################
      # 00 – Foundation / Normalize / Inject Pitcher IDs / Rebuild SP ctx
      ####################################################################
      - name: 00_foundation_normalize
        run: |
          set -euo pipefail
          mkdir -p summaries/00_foundation logs data/_projections data/end_chain/final data/temp_inputs
          python scripts/todaysgames.py                                2>&1 | tee logs/00_todaysgames.log
          python scripts/normalize_todays_games.py                     2>&1 | tee logs/01_normalize_todays_games.log
          python scripts/inject_pitcher_ids_into_games.py              2>&1 | tee logs/02_inject_pitcher_ids.log
          python scripts/rebuild_startingpitchers.py                   2>&1 | tee logs/03_rebuild_startingpitchers.log

      ####################################################################
      # 01 – Split Home/Away & Stage
      ####################################################################
      - name: 01_split_and_stage
        run: |
          set -euo pipefail
          python scripts/splithome.py             2>&1 | tee logs/04_splithome.log
          python scripts/splitaway.py             2>&1 | tee logs/05_splitaway.log
          python scripts/bet_prep_1.py            2>&1 | tee logs/06_bet_prep_1.log

      ####################################################################
      # 02 – Context / Fixups + Normalize/Tag (plus park factor generation)
      ####################################################################
      - name: 02_context_and_fixes
        run: |
          set -euo pipefail
          if [ -f scripts/fix_team_names.py ]; then python scripts/fix_team_names.py | tee logs/07_fix_team_names.log; fi
          python scripts/normalize_names.py                       2>&1 | tee logs/08_normalize_names.log
          python scripts/tag_master_files.py                      2>&1 | tee logs/09_tag_master_files.log
          python scripts/normalize_lineups.py                     2>&1 | tee logs/10_normalize_lineups.log
          python scripts/build_batters_today_from_lineups.py      2>&1 | tee logs/11_build_batters_today_from_lineups.log
          python scripts/normalize_batters_for_builder.py         2>&1 | tee logs/12_normalize_batters_for_builder.log
          python scripts/deduplicate_normalized.py                2>&1 | tee logs/13_deduplicate_normalized.log
          python scripts/validate_tagged_players.py               2>&1 | tee logs/14_validate_tagged_players.log
          python scripts/update_game_time.py                      2>&1 | tee logs/15_update_game_time.log
          python scripts/finalize_todaysgames_types_and_pf.py     2>&1 | tee logs/16_finalize_todaysgames_types_and_pf.log
          python scripts/apply_park_adjustment.py                 2>&1 | tee logs/17_apply_park_adjustment.log
          python scripts/apply_pitcher_park_adjustment.py         2>&1 | tee logs/18_apply_pitcher_park_adjustment.log
          python scripts/clean_and_preprocess_games.py            2>&1 | tee logs/19_clean_and_preprocess_games.log
          python scripts/pit1.py                                  2>&1 | tee logs/20_pit1.log
          python scripts/chain_load_data.py                       2>&1 | tee logs/21_chain_load_data.log
          python scripts/prep_merge.py                            2>&1 | tee logs/22_prep_merge.log

      ####################################################################
      # 03 – Weather Inputs (MANDATORY)
      ####################################################################
      - name: 03_weather_inputs (MANDATORY)
        run: |
          set -euo pipefail
          python scripts/get_weather_data.py                    2>&1 | tee logs/23a_get_weather_data.log
          python scripts/generate_weather_csv.py                2>&1 | tee logs/23b_generate_weather_csv.log
          python scripts/weather_data_fix.py                    2>&1 | tee logs/23c_weather_data_fix.log
          python scripts/finalize_weather_outputs.py            2>&1 | tee logs/23d_finalize_weather_outputs.log
          python scripts/normalize_pitcher_weather_outputs.py   2>&1 | tee logs/23e_normalize_pitcher_weather_outputs.log

      ####################################################################
      # 04 – Weather Adjustments (MANDATORY)
      ####################################################################
      - name: 04_weather_adjustments_batters (MANDATORY)
        run: |
          set -euo pipefail
          python scripts/apply_weather_adjustment.py            2>&1 | tee logs/24_apply_weather_adjustment_batters.log

      - name: 04_weather_adjustments_pitchers (MANDATORY)
        run: |
          set -euo pipefail
          mkdir -p summaries/pitchers_adjust
          : > summaries/pitchers_adjust/missing_woba.txt
          python scripts/apply_pitcher_weather_adjustment.py    2>&1 | tee logs/25_apply_weather_adjustment_pitchers.log

      - name: 04_weather_combine_outputs (MANDATORY)
        run: |
          set -euo pipefail
          python scripts/combine_batter_weather_park.py         2>&1 | tee logs/26_combine_batter_weather_park.log
          python scripts/combine_pitcher_weather_park_home.py   2>&1 | tee logs/27_combine_pitcher_weather_park_home.log
          python scripts/combine_pitcher_weather_park_away.py   2>&1 | tee logs/28_combine_pitcher_weather_park_away.log

      ####################################################################
      # 05 – Prep Summary & Commit
      ####################################################################
      - name: 05_prep_summary
        run: |
          set -euo pipefail
          mkdir -p summaries
          games_count=$(python -c "import pandas as pd; print(pd.read_csv('data/raw/todaysgames_normalized.csv')['game_id'].nunique())" || echo "ERR")
          weather_count=$(python -c "import pandas as pd; print(pd.read_csv('data/weather_adjustments.csv')['game_id'].nunique())" || echo "ERR")
          {
            echo "=== Pipeline Prep Summary (00-05) ==="
            echo "Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            echo
            echo "[00] Foundation/Normalize/Inject/Rebuild: OK"
            echo "[01] Split & Stage: OK"
            echo "[02] Context + Normalize/Tag + PF: OK"
            echo "[03] Weather Inputs: OK"
            echo "[04] Weather Adjustments + Combines: OK"
            echo
            echo "--- Weather Audit ---"
            echo "Games today (unique game_id): $games_count"
            echo "Weather rows (unique game_id): $weather_count"
            echo
            echo "--- Key files present ---"
            ls -lah data/_projections || true
            ls -lah data/end_chain/final || true
            echo
            echo "--- Recent logs ---"
            tail -n +1 logs/*.log | sed -e 's/\x1b\[[0-9;]*m//g' | tail -n 200 || true
          } > summaries/pipeline-prep_summary.txt

      - name: Commit artifacts
        env:
          TARGET_BRANCH: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else:
            git commit -m "Prep: 00-05 with normalize/tag/adjust + park_factor generation + weather"
            git push --force-with-lease origin HEAD:${TARGET_BRANCH}
          fi
