name: Run Split Batters

on:
  workflow_dispatch:

jobs:
  split_batters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt unidecode

      - name: Run split_batters_by_home_away.py
        run: |
          mkdir -p summaries
          python scripts/split_batters_by_home_away.py
