name: Score Bets (MLB API)

on:
  workflow_dispatch:

jobs:
  score-bets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Compute target date (yesterday)
        id: get-date
        run: echo "date=$(date -d 'yesterday' +%F)" >> $GITHUB_ENV

      - name: Score GAME bets (that day via MLB API)
        run: |
          python scripts/score_game_bets_range.py \
            --date ${{ env.date }} \
            --api "MLB_API_BASE"

      - name: Score PLAYER bets (MLB API)
        run: |
          python scripts/score_player_bets.py \
            --date ${{ env.date }} \
            --api "MLB_API_BASE"

      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/bets/bet_history/*.csv
          git commit -m "Scored bets for ${{ env.date }}" || echo "No changes to commit"
          git push
