name: Scrape Starting Pitchers from BR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"  # 10 AM ET

jobs:
  scrape-pitchers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape_starting_pitchers_bref.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/daily/todays_pitchers.csv
          git commit -m "Update today's pitchers from BR" || echo "No changes to commit"
          git push
