name: Standardize Team Names

on:
  workflow_dispatch:

jobs:
  standardize-names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas

      - name: Run team name standardizer
        run: python scripts/apply_team_name_mapping.py

      - name: Commit and push standardized files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/raw/todaysgames_normalized.csv
          git add data/Data/stadium_metadata.csv
          git commit -m "Standardized team names" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
