name: Tag Uploaded Master Files

on:
  workflow_dispatch:

jobs:
  tag-master-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pandas
        run: pip install pandas

      - name: Run tag_master_files.py
        run: python tag_master_files.py

      - name: Commit and push tagged CSVs
        run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    
    # Add all .csv files under tagged (wildcard avoids hard fails)
    git add data/tagged/*.csv || true

    # Only commit if there are changes
    git diff --cached --quiet || git commit -m "Tag master batter/pitcher files"
    git push
