name: Update Todays Games CSV

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script to create todaysgames.csv
        run: |
          python scripts/todaysgames.py --out todaysgames.csv

      - name: Verify output exists
        run: |
          ls -la
          test -s todaysgames.csv

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add todaysgames.csv
          git status
          git diff --quiet && git diff --staged --quiet && echo "No changes to commit." && exit 0
          git commit -m "Update todaysgames.csv"
          git pull --rebase origin "${{ github.ref_name }}"
          git push origin HEAD:"${{ github.ref_name }}"
