name: Update Lineups CSV

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run todayslineups.py
        run: |
          python scripts/todayslineups.py

      - name: Commit and push lineups.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/raw/lineups.csv
          git diff --staged --quiet || git commit -m "Update lineups.csv"
          git push origin HEAD:${{ github.ref_name }}
