name: Update Todays Games CSV

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to create todaysgames.csv
        run: |
          set -euo pipefail
          python -u scripts/todaysgames.py --out todaysgames.csv

      - name: Ensure CSV exists
        run: |
          test -s todaysgames.csv || { echo "todaysgames.csv missing/empty"; exit 1; }
          head -n 5 todaysgames.csv || true

      - name: Commit and push (always create a commit)
        run: |
          set -e
          BRANCH="${{ github.ref_name }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Force-add even if ignored
          git add --force todaysgames.csv

          # If there are staged changes, commit them; otherwise make an empty commit
          if git diff --cached --quiet; then
            echo "No content changes; creating an empty keep-alive commit."
            git commit --allow-empty -m "Keep todaysgames.csv (no content change) [run $GITHUB_RUN_ID]"
          else
            git commit -m "Update todaysgames.csv [run $GITHUB_RUN_ID]"
          fi

          # Rebase to avoid non-fast-forward, then push to the same branch the workflow ran on
          git pull --rebase origin "$BRANCH" || true
          git push origin HEAD:"$BRANCH"
