name: Update Game Time

on:
  workflow_dispatch:

jobs:
  update-game-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas

      - name: Run update script
        run: python scripts/update_game_time.py

      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/Data/stadium_metadata.csv
          git add game_time_update_log.csv
          git commit -m "Update game_time in stadium_metadata" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
