name: Weather Data Fetch

on:
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests python-dateutil pytz tzdata

      - name: Run Weather Script
        run: python scripts/get_weather_data.py

      - name: Commit weather output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add data/weather_adjustments.csv || true
          git commit -m "Auto-commit: updated weather data" || echo "No changes to commit"
          git push || echo "No push needed"
